server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:twitterdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-evyrhl30mk03e5xh.us.auth0.com/
          audiences: https://twitter-like-api

springdoc:
  swagger-ui:
    path: /swagger-ui.html